FSA-2004-Akatsuki-Dev-Clan/ClassSync

server/db/models/classes.js
server/db/models/index.js
server/db/models/sessions.js
server/db/models/student-class.js
server/db/models/student-session.js
server/db/models/students.js
server/db/models/teachers.js

feat: single models defined

---

server/db/models/teachers.js

fix: update teacher sequelize hooks

---

client/components/index.js
client/components/user-media.js
client/routes.js
client/socket.js
public/index.html
server/db/models/teachers.js
server/socket/index.js

feat: getUserMedia through sockets

---

.travis.yml

feat: travis continuous deployment

---

server/auth/index.js
server/db/models/students.js
server/db/models/teachers.js
teacher-seed.js

fix: master merge conflicts

---

client/socket.js

* As a User, we want to be able to have our data sent to the initializer by individual socket
*Set interval function used via socket Id default passed in to socket emitt method.
*Will change to student id once component is built
Partial resolve Issue #30

feature: dataInterval

---

package-lock.json
server/db/models/classes.js
server/db/models/sessions.js
server/db/models/student-session.js
server/db/models/students.js

*As a teacher we want to have our data for each session live somewhere I can look to later look at.
*As a backend Engineer, we want our data from each live session to be saved in the database to serve up to the client quick metrics for the teacher to see total engagement from the session and each student's average.
---
Partial Res: Issue #41 

Model definitions

---

server/socket/index.js

sessionData object description comment in socket file

doc: comment on socket index file to describe sessionData object

---

client/components/single-student.js
client/components/table.js

feat: table data on single student component

---

client/components/single-student.js
client/components/table.js
client/components/teacher-dash/all-students.js
client/routes.js
client/store/single-student.js
student-seed.js

* As a teacher I want to be able to see a single student's information in my dashboard from a live session
*As engineers we were able to render components to show a single student view once clicking on a student name that showed the realtime data for the student's engagement
---

Feat sing view

---

client/components/single-stud-table.js
client/components/single-student.js
student-seed.js

single student table chart that updates with the live session data

feat: single student table chart

---

client/socket/student.js
client/socket/teacher.js
client/store/liveSession.js
client/store/liveStudents.js
client/store/user.js
client/store/user.spec.js
server/auth/index.js
server/socket/index.js
student-seed.js

--Socket architecture accounts for logouts/logins, refreshes
--Session data collection persists through disconnections and reconnected teacher and students are able to continue with data collection
--End session now clears the live data in redux store and stops the server data sending interval

Live session fixes

---

client/components/teacher-dash/all-students.js
client/components/teacher-dash/chart.js

--set Y-axis ranges on charts
--Dummy name for blank names in live student list
--changed color of trend line in chart

fix: axes and colors on charts

---

client/components/single-stud-table.js
client/components/single-student.js
client/components/teacher-dash/chart.js

style: improved chart layout

---

client/components/student-monitor.js
client/socket/student.js
client/socket/teacher.js
package-lock.json
package.json

* as a student I want to have some activity on the page as I'm being monitored
*As an engineer, we want students to be able to interact with the page as monitored.
---

feature: Google Sheet Quiz Embed

---

client/socket/index.js
client/socket/student.js
client/socket/teacher.js
client/store/liveSession.js
client/store/liveStudents.js
client/store/user.js
server/socket/index.js

--comments added to document functionality in sockets, and redux store for creating live session data

doc: comments explaining socket and session data functionality

---

script/seed.js
server/db/models/index.js
session-seed.js
student-seed.js
student-session-seed.js

feat: seeded instead of making comp

---

client/components/teacher-dash/live-session.js
client/components/teacher-dash/single-student.js
client/student-monitor.js

--Set audio back to true for media device access
--Tables and charts are rendered conditionally based on presence of data

Button loads chart axis

---

client/components/teacher-dash/all-students.js
client/components/teacher-dash/live-session.js
client/components/teacher-dash/session-form.js
client/socket/student.js
client/socket/teacher.js
client/store/user.js
server/socket/index.js

--Adjusted user object passed through socket to logout function on server

fix: logout function fixed

---

client/components/chart.js
client/components/student-session.js
client/components/teacher-dash/session-form.js
client/components/teacher-dash/single-student.js
client/components/teacher-dash/teacher-dash.js
client/socket/teacher.js
client/store/status.js
client/store/user.js
server/socket/index.js

--Minor component adjustments for teacher page
--Chart labels/axes/colorizing improved
--Added activity title to redux store
--Minor socket edits

Chart components

---

client/components/teacher-dash/historical-single-student-session.js
client/components/teacher-dash/historical-single-student.js
client/store/liveStudents.js

Reverts FSA-2004-Akatsuki-Dev-Clan/ClassSync#150

Revert "feat: single student single session graph"

---

client/components/teacher-dash/historical-single-student-session.js

Reverts FSA-2004-Akatsuki-Dev-Clan/ClassSync#153

Revert "Safety: Back Up for Student History"

---

client/components/teacher-dash/historical-single-student-session.js
client/components/teacher-dash/historical-single-student.js
package.json

fix: merge conflicts and missing files

---

client/store/specs/student.spec.js
client/store/specs/teacher.spec.js

fix: student test specs

---

client/components/session.js
client/components/teacher-dash/historical-single-student-session.js
client/components/teacher-dash/historical-single-student.js
client/socket/teacher.js
server/api/session.js
server/api/students.js

--ordering of sessions/students

Final test

---

client/components/chart.js
client/components/homepage.js
client/components/navbar.js
client/components/single-table.js
client/components/table.js
client/components/teacher-dash/accordion.js
client/components/teacher-dash/historical-session.js
client/components/teacher-dash/historical-single-student.js
client/components/teacher-dash/live-session.js
client/components/teacher-dash/teacher-dash.js

--Resolved improper selection of student from ordered list
--chart timescale fix

Corrections
